source/facets.toml

[Jira](https://jira.mongodb.org/browse/DOCSP-35450)
[Staging link](https://preview-mongodbsarahemlin.gatsbyjs.io/scala/DOCSP-35450/)
[Build log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f22b036fc5f04850463ec5)

DOCSP-35450 programmatic tagging script for scala repo

---

.github/pull_request_template.md
source/installation.txt

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java-rs/blob/master/REVIEWING.md)
JIRA - <https://jira.mongodb.org/browse/DOCSP-38223>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38223-installation/installation/>

DOCSP-38223: installation

---

source/get-started.txt
source/get-started/primer.txt
source/get-started/quickstart.txt
source/includes/install-note.rst
source/includes/obs-note.rst

JIRA - <https://jira.mongodb.org/browse/DOCSP-38221>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38221-qs/get-started/quickstart/>

DOCSP-38221: quickstart

---

source/bson.txt
source/bson/macros.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38477>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38477-bson-macros/bson/macros/>

DOCSP-38477: bson macros

---

source/get-started.txt
source/get-started/qs-case-class.txt
source/get-started/quickstart.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38220>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38220-case-class-qs/get-started/qs-case-class/>

DOCSP-38220: Case class QS

---

snooty.toml
source/index.txt
source/tutorials.txt
source/tutorials/connect.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38219>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38219-connect/tutorials/connect/>

DOCSP-38219: connect to mongodb

---

source/bson.txt
source/bson/extended-json.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38478>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38478-bson-ejson/bson/extended-json/>

DOCSP-38478: bson ext json

---

source/includes/connect-section.rst
source/tutorials.txt
source/tutorials/indexes.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38217>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38217-indexes/tutorials/indexes/>

DOCSP-38217: indexes

---

snooty.toml
source/tutorials.txt
source/tutorials/bulk-writes.txt
source/tutorials/write-ops.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38215>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38215-write/tutorials/write-ops/>
https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38215-write/tutorials/bulk-writes/

DOCSP-38215: write operations

---

source/includes/prereq-restaurants.rst
source/tutorials.txt
source/tutorials/read-ops.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38216>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38216-read-ops/tutorials/read-ops/

DOCSP-38216: read operations

---

source/tutorials.txt
source/tutorials/encrypt.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38213>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38213-csfle/tutorials/encrypt/>

DOCSP-38213: encryption

---

source/tutorials.txt
source/tutorials/text-search.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38211>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38211-text/tutorials/text-search/>

DOCSP-38211: text search

---

source/tutorials.txt
source/tutorials/geospatial.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38210>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38210-geospatial/tutorials/geospatial/>

DOCSP-38210: geospatial

---

source/tutorials.txt
source/tutorials/gridfs.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38209>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38209-gridfs/tutorials/gridfs/>

DOCSP-38209: gridfs

---

source/tutorials/connect.txt
source/tutorials/connect/tls.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38207>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38207-tls/tutorials/connect/tls/>

DOCSP-38207: tls/ssl

---

source/tutorials.txt
source/tutorials/command.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38208>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38208-command/tutorials/command/>

DOCSP-38208: run a command

---

source/tutorials/connect.txt
source/tutorials/connect/authentication.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38206>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38206-auth/tutorials/connect/authentication/>

DOCSP-38206: authentication

---

source/tutorials/connect.txt
source/tutorials/connect/compression.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38205>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38205-compression/tutorials/connect/compression/>

DOCSP-38205: compressors

---

source/index.txt
source/reference.txt
source/reference/logging.txt
source/reference/monitoring.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38204>
Staging -
https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38204-logging-monitoring/reference/logging/
https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38204-logging-monitoring/reference/monitoring/

DOCSP-38204: logging & monitoring

---

source/reference.txt
source/reference/observables.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38757>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38757-observables/reference/observables/>

DOCSP-38757: observables

---

snooty.toml
source/builders.txt
source/builders/filters.txt
source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38758>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38758-filters/builders/filters/>
https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38758-filters/builders/

DOCSP-38758: filters builders

---

source/builders.txt
source/builders/sorts.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38760>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38760-sorts/builders/sorts/>

DOCSP-38760: sorts builders

---

source/builders.txt
source/builders/indexes.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38764>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38764-indexes-builders/builders/indexes/>

DOCSP-38764: indexes builders

---

source/builders.txt
source/builders/aggregates.txt
source/builders/filters.txt
source/builders/indexes.txt
source/builders/projections.txt
source/builders/sorts.txt
source/builders/updates.txt
source/get-started.txt
source/get-started/quickstart.txt
source/reference.txt
source/reference/monitoring.txt
source/tutorials.txt
source/tutorials/db-coll.txt
source/tutorials/indexes.txt
source/tutorials/read-ops.txt
source/tutorials/write-ops.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38201>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38201-cleanup/

DOCSP-38201: cleanup

---

source/index.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-38807>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/scala/DOCSP-38807-server-3.6-eol/whats-new/

DOCSP-38807: mdb 3.6 deprecation

---

source/index.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-40577
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/scala/DOCSP-40577-broken-link/
- [] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

DOCSP-40577 Fix broken JavaRS link

---

source/installation.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-40638
Staging - https://preview-mongodbstephmarie17.gatsbyjs.io/scala/docsp-40638-installInstructions/

DOCSP-40638 update installation instructions

---

source/index.txt
source/issues-and-help.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44292>
Staging - https://deploy-preview-60--docs-scala.netlify.app/issues-and-help/

DOCSP-44292: add i&h

---

snooty.toml
source/includes/usage-examples/SampleWriteApp.scala
source/includes/usage-examples/WriteCodeExamples.scala
source/includes/usage-examples/sample-app-intro.rst
source/index.txt
source/write.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42321>
Staging - <https://deploy-preview-55--docs-scala.netlify.app/write/>

DOCSP-42321: Insert landing page

---

source/includes/write/bulk-write.scala
source/write.txt
source/write/bulk-write.txt
source/write/insert.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42325>
Staging - <https://deploy-preview-68--docs-scala.netlify.app/write/bulk-write/>

DOCSP-42325: Bulk Write

---

snooty.toml
source/databases-collections.txt
source/includes/databases-collections/databases-collections.scala
source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42317>
Staging - <https://deploy-preview-77--docs-scala.netlify.app/databases-collections/>

DOCSP-42317: Databases and Collections

---

source/includes/read/change-streams.scala
source/read.txt
source/read/change-streams.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42335
Staging - https://deploy-preview-69--docs-scala.netlify.app/read/change-streams/

DOCSP-42335: Change streams

---

source/databases-collections.txt
source/databases-collections/run-command.txt
source/includes/run-command.scala
source/index.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42311
Staging - https://deploy-preview-75--docs-scala.netlify.app/databases-collections/run-command/

DOCSP-42311: Run a Command

---

source/aggregation.txt
source/includes/aggregation.scala
source/index.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42342
Staging - https://deploy-preview-71--docs-scala.netlify.app/aggregation/

DOCSP-42342: Aggregation

---

snooty.toml
source/connect/stable-api.txt
source/includes/connect/stable-api.scala

JIRA - <https://jira.mongodb.org/browse/DOCSP-42316>
Staging - <https://deploy-preview-81--docs-scala.netlify.app/connect/stable-api/>

DOCSP-42316: Stable API

---

source/includes/indexes/atlas-search-index.scala
source/indexes/atlas-search-index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42341>
Staging - <https://deploy-preview-82--docs-scala.netlify.app/indexes/atlas-search-index/>

DOCSP-42341: Atlas Search Indexes

---

source/index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-42347>
Staging - <https://deploy-preview-84--docs-scala.netlify.app/>

Uncomment link to compat tables on landing page

---

snooty.toml
source/includes/usage-examples/ReadCodeExamples.scala
source/includes/usage-examples/SampleReadApp.scala
source/index.txt
source/read.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-40287>
Staging - <https://deploy-preview-85--docs-scala.netlify.app/read/>

DOCSP-40287: Read landing page

---

source/includes/read-write-pref.scala
source/index.txt
source/read-write-pref.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42319
Staging - https://deploy-preview-79--docs-scala.netlify.app/read-write-pref/

DOCSP-42319: Read and write settings

---

source/includes/write/transaction.scala
source/write/transactions.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42349
Staging - https://deploy-preview-89--docs-scala.netlify.app/write/transactions/

DOCSP-42349: Transactions

---

source/includes/observables.scala
source/index.txt
source/observables.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42334
Staging - https://deploy-preview-86--docs-scala.netlify.app/observables/

DOCSP-42334: Observables

---

source/aggregation.txt
source/includes/aggregation.scala

JIRA - https://jira.mongodb.org/browse/DOCSP-24494
Staging - https://deploy-preview-90--docs-scala.netlify.app/aggregation/#run-an-atlas-full-text-search

DOCSP-24494: Atlas search section

---

source/bson.txt
source/builders.txt
source/get-started.txt
source/index.txt
source/reference.txt
source/tutorials.txt
source/tutorials/connect.txt
source/tutorials/write-ops.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44952 >
Staging - <https://deploy-preview-87--docs-scala.netlify.app>

DOCSP-44952 TOC Relabel

---

source/bson.txt
source/builders.txt
source/get-started.txt
source/index.txt
source/reference.txt
source/tutorials.txt
source/tutorials/connect.txt
source/tutorials/write-ops.txt

* TOC Relabel
* review comments on builders
* suggestion
(cherry picked from commit 2ca57324c37329c7add0497b1f532f9d15a772f8)
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

[Backport v5.0] DOCSP-44952 Shorten TOC

---

source/bson.txt
source/builders.txt
source/get-started.txt
source/index.txt
source/reference.txt
source/tutorials.txt
source/tutorials/connect.txt
source/tutorials/write-ops.txt

* TOC Relabel
* review comments on builders
* suggestion
(cherry picked from commit 2ca57324c37329c7add0497b1f532f9d15a772f8)
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

[Backport v4.x] DOCSP-44952 Shorten TOC

---

source/connect.txt
source/databases-collections.txt
source/index.txt
source/indexes.txt
source/monitoring.txt
source/read.txt
source/security.txt
source/write.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-45354
Staging - https://deploy-preview-94--docs-scala.netlify.app/

DOCSP-45354: TOC labels

---

config/redirects

JIRA - https://jira.mongodb.org/browse/DOCSP-45605

DOCSP-45605: Redirects for standardized docs

---

source/includes/write/delete.scala
source/write/delete.txt

<https://jira.mongodb.org/browse/DOCSP-46057>
Staging - <https://deploy-preview-103--docs-scala.netlify.app/write/delete/>

DOCSP-46057: Fix deleteOne() code sample

---

source/write/transactions.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-45882>
Staging - <https://deploy-preview-104--docs-scala.netlify.app/write/transactions/>

DOCSP-45882: Transactions parallelism admonition

---

source/bson.txt
source/bson/macros.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-46731>
Staging - https://deploy-preview-107--docs-scala.netlify.app/bson/macros/

DOCSP-46731 Too Short Title: Macros

---

source/tutorials/gridfs.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-46734>
Staging - https://deploy-preview-110--docs-scala.netlify.app/tutorials/gridfs/

DOCSP-46734 Too Short Title: GridFS

---

source/builders/aggregates.txt
source/builders/filters.txt
source/builders/indexes.txt
source/builders/projections.txt
source/builders/sorts.txt
source/builders/updates.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-46732>
Staging - https://deploy-preview-108--docs-scala.netlify.app/builders/filters/
(Updated titles for all in the  Builders section)

DOCSP-46732 Too Short Title: Builders

---

source/get-started/primer.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-46733>
Staging - https://deploy-preview-109--docs-scala.netlify.app/get-started/primer/

DOCSP-46733 Too Short Title: Primer

---

source/index.txt
source/read.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
Staging - <https://deploy-preview-114--docs-scala.netlify.app/read/>

[Scala] Remove "MongoDB" from page title

---

snooty.toml

JIRA - <https://jira.mongodb.org/browse/DOCSP-48301>

DOCSP-48301: Update snooty title

---

source/connect/connection-targets.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-48765>
Staging - https://deploy-preview-124--docs-scala.netlify.app/connect/connection-targets/#replica-sets

DOCSP-48765: docker note

---

source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-49719>
Staging - https://deploy-preview-130--docs-scala.netlify.app/whats-new/#std-label-scala-version-5.5
**Same changes approved in** https://github.com/mongodb/docs-java-rs/pull/130

DOCSP-49719: connectTimeoutMS option for TLS

---

snooty.toml
source/connect.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-51285
<li><a href=https://deploy-preview-144--docs-scala.netlify.app/connect>connect</a></li>

DOCSP-51285: noindex Connect landing page
